services:
  - type: web
    name: crm-backend
    env: node
    repo: https://github.com/8619747559rahulkumawat/crm-application.git
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: "mongodb+srv://rahulkumar8600:wQvzL8XHx8mF4HdS@cluster0.exeq63f.mongodb.net/crm?retryWrites=true&w=majority"
      - key: JWT_SECRET
        value: "your_super_secure_jwt_secret_key_for_production_change_this"
      - key: PORT
        value: 5000
